name: r_flutter
version: 0.8.1
description: Generate constants for resources which require using them as a String like fonts and assets.

homepage: https://github.com/timfreiheit/r_flutter
environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  args: any
  dart_style: any
  path: any
  yaml: any
  recase: any
  build: any
  build_config: any

dev_dependencies:
  test: any
  build_test: any
  lint: ^1.0.0
